# Generated by Django 4.1.7 on 2023-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='created',
            field=models.DateTimeField(default='2023-06-19T20:17:25.572507Z'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='modified',
            field=models.DateTimeField(default='2023-06-19T20:17:25.572507Z'),
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
