# Generated by Django 4.1.7 on 2023-06-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_group_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='group_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat'),
        ),
    ]
