# Generated by Django 4.1.7 on 2023-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_created_groupchat_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
