# Generated by Django 4.1.7 on 2023-06-22 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_groupchat_created_alter_groupchat_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 51, 16, 68276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userimage',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 51, 16, 68276, tzinfo=datetime.timezone.utc)),
        ),
    ]
