# Generated by Django 4.1.7 on 2023-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userimage_created_userimage_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
